using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace MWMS.Services.Maintenance.InfrastructureLayer.MongoDB
{
    public class Customer
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }
        public string CustomerId { get; set; }
        public string Name { get; set; }
        public string TelephoneNumber { get; set; }
    }
}
